// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMueFinsHlA7BP1uuu3o0afUjM1hlYQWk',
    appId: '1:344552312153:android:5e44db414b6413fd9ed048',
    messagingSenderId: '344552312153',
    projectId: 'laundry-acc',
    storageBucket: 'laundry-acc.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiyQsGuGwQA56zZtpKDNQf13QDjsiH1N4',
    appId: '1:344552312153:web:27eded9e7aab2a9a9ed048',
    messagingSenderId: '344552312153',
    projectId: 'laundry-acc',
    authDomain: 'laundry-acc.firebaseapp.com',
    storageBucket: 'laundry-acc.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMdQKNZYdrh60glZ-uXR93U9n5_TB1gZQ',
    appId: '1:344552312153:ios:cfe698a0607b2b9b9ed048',
    messagingSenderId: '344552312153',
    projectId: 'laundry-acc',
    storageBucket: 'laundry-acc.firebasestorage.app',
    iosBundleId: 'com.example.tucksalonapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMdQKNZYdrh60glZ-uXR93U9n5_TB1gZQ',
    appId: '1:344552312153:ios:cfe698a0607b2b9b9ed048',
    messagingSenderId: '344552312153',
    projectId: 'laundry-acc',
    storageBucket: 'laundry-acc.firebasestorage.app',
    iosBundleId: 'com.example.tucksalonapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiyQsGuGwQA56zZtpKDNQf13QDjsiH1N4',
    appId: '1:344552312153:web:ced4cbd18ece41739ed048',
    messagingSenderId: '344552312153',
    projectId: 'laundry-acc',
    authDomain: 'laundry-acc.firebaseapp.com',
    storageBucket: 'laundry-acc.firebasestorage.app',
  );

}